# Generated by Django 3.1.5 on 2021-06-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('alt_description_pt', models.CharField(max_length=300)),
                ('alt_description_en', models.CharField(max_length=300)),
                ('alt_description_es', models.CharField(max_length=300)),
                ('audio_description_pt', models.FileField(upload_to='')),
                ('audio_description_en', models.FileField(upload_to='')),
                ('audio_description_es', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'guides',
            },
        ),
    ]
