# Generated by Django 3.1.5 on 2021-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('alt_description', models.CharField(max_length=300)),
                ('audio_description', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'guides',
            },
        ),
    ]
