# Generated by Django 3.1.5 on 2021-06-18 20:05

from django.db import migrations, models
import guidesapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('guidesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='audio_description_en',
            field=models.FileField(upload_to='', validators=[guidesapp.validators.validate_file_audio]),
        ),
        migrations.AlterField(
            model_name='guide',
            name='audio_description_es',
            field=models.FileField(upload_to='', validators=[guidesapp.validators.validate_file_audio]),
        ),
        migrations.AlterField(
            model_name='guide',
            name='audio_description_pt',
            field=models.FileField(upload_to='', validators=[guidesapp.validators.validate_file_audio]),
        ),
    ]
