# Generated by Django 3.1.5 on 2021-06-18 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidesapp', '0002_auto_20210618_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='audio_description_es',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
